### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by Myszax** [Scordo/TS3QueryLib.Net#33]
Hello.
I've encountered strange problem. When I want to create channel via CreateChannel method, but I have exception. Channel has been created, but exception is raised. 
My code looks like:
```
ChannelModification cm = new ChannelModification
{
	Name = "randomName",
	Description = "desc-test",
	IsPermanent = true
};
var response = _query.CreateChannel(cm);
```
StackTrace:
```
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToUInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.ExtensionMethods.ChangeType[T](Object sourceValue, T defaultValue, IFormatProvider formatProvider)
   at System.ExtensionMethods.ChangeTypeInvariant[T](Object sourceValue, T defaultValue)
   at TS3QueryLib.Core.Common.Responses.SingleValueResponse`1.FillFrom(String responseText, Object[] additionalStates)
   at TS3QueryLib.Core.Common.Responses.ResponseBase`1.Parse(String response, Object[] additionalStates)
   at TS3QueryLib.Core.Server.QueryRunner.CreateChannel(ChannelModification channelModification)
```
I've tried to change my thread culture to en-US, but still not works.

**Comment by Scordo** [comment]
Hi Myszax,

sorry for the late response. I tried to reproduce the error with your code but failed.
Which version of the server and the lib are you using?

Regards,
Scordo

**Comment by Myszax** [comment]
I am using the newest 1.2.2.0 of course. I know it's hard to reproduce. When I am trying to do this in new project I can't.
I've got simple method for creating channel. This method is invoked by an event. Of course I'm using AsyncTCPDispacher.

**Comment by Scordo** [comment]
I'll throw a wrapper Exception in a future build if an exception is thrown by the Parse-Method.
This exception will have the raw Response-String in the Exception-Text. So we can find the real cause.

**Comment by Myszax** [comment]
Ok so I am waiting :)

**Comment by Scordo** [comment]
Please use AwaitableQueryDispatcher. There is a conceptional problem in the old AsyncTcpDispatcher which I cant fix which is the cause for this problem.
