### ISSUE TITLE
Could not cast parameter with name 'client_icon_id' and value '' to target type of 'System.UInt32

### ISSUE THREAD

**Issue by TimmKroe** [Scordo/TS3QueryLib.Net#40]
I get the following error
```
System.InvalidCastException: Could not cast parameter with name 'client_icon_id' and value '' to target type of 'System.UInt32'. ---> System.InvalidCastException: Can not cast null value of parameter 'client_icon_id' to target type 'System.UInt32'.
   at TS3QueryLib.Core.CommandHandling.CommandParameterGroup.ConvertValue[T](String parameterName, String parameterValue)
   --- End of inner exception stack trace ---
   at TS3QueryLib.Core.CommandHandling.CommandParameterGroup.ConvertValue[T](String parameterName, String parameterValue)
   at TS3QueryLib.Core.Server.Responses.ClientInfoBaseResponse`1.FillFrom(String responseText, Object[] additionalStates)
   at TS3QueryLib.Core.Server.Responses.ClientDbInfoResponse.FillFrom(String responseText, Object[] additionalStates)
   at TS3QueryLib.Core.Common.Responses.ResponseBase`1.Parse(String response, Object[] additionalStates)
```
If more code is needed just ask.

**Comment by Scordo** [comment]
Seems to be that client_icon_id can be <null>.  Changes todo:

`public uint IconId { get; protected set; }` --> `public uint? IconId { get; protected set; }`
`IconId = list.GetParameterValue<uint>("client_icon_id"); ` --> `IconId = list.GetParameterValue<uint?>("client_icon_id"); `

Here: 
https://github.com/Scordo/TS3QueryLib.Net/blob/d7027a4e08647513b59db52ffde00ea0f11ca967/TS3QueryLib.Core.Framework/Server/Responses/ClientInfoBaseResponse.cs

**Comment by TimmKroe** [comment]
@Scordo Should I fix it or do you want to do it ?

**Comment by TimmKroe** [comment]
@Scordo Ok then give me a minute :D

**Comment by Scordo** [comment]
Dont forget the changelog ;-)

**Comment by TimmKroe** [comment]
Of course :D

**Comment by TimmKroe** [comment]
Fixed

**Comment by Scordo** [comment]
Can you pleas also add the "Opus changelog text" to the changelog.txt? :-D

**Comment by TimmKroe** [comment]
yes :D
